version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysqlcontainer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "store"
      MYSQL_DATABASE: "store"
      MYSQL_USER: "store"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: "db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data: