version: '3.4'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container-api
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=forum_hub
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql: