version: "3.5"

services:
    db:
      image: mysql:8.0
      container_name: mysql_container_web
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=vollmed_web
      volumes:
        - mysql:/var/lib/mysql
      ports:
        - "3306:3306"

volumes:
  mysql:
