CREATE TABLE employees_audit(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(75) NOT NULL,
    old_name VARCHAR(75) NOT NULL,
    birthday TIMESTAMP NOT NULL,
    old_birthday TIMESTAMP NOT NULL,
    salary DECIMAL(10,2) NOT NULL,
    old_salary DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8;